export NODE_APP_PREFIX="MR"
export MR_ENV="development"
export MR_APP_PORT="3000"
export MR_API_REMOTE_HOST="https://mirari.ru"
export MR_API_REMOTE_PATH="/"
export MR_API_ROOT="api"
export NODE_ENV="development"
